### ISSUE TITLE
Math expressions don't work in dashboard panels

### ISSUE THREAD

**Issue by kostrse** [grafana/azure-data-explorer-datasource#503] opened 2022-10-22 01:00 UTC
**What happened**:

Any math expressions result in error "e.replace is not a function"

**How to reproduce it (as minimally and precisely as possible)**:

1. Add two queries A and B which successfully return data
2. Add an expression, "Math", "$A + $B"
3. See the error "e.replace is not a function"

**Screenshots**

![Screenshot_20221021_053527](https://user-images.githubusercontent.com/1131253/197309041-0b2d7297-1f9d-4c83-b1d9-db138a06a218.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.1.x
- Plugin version: main

**Comment by kostrse** [comment] 2022-10-22 01:01
There's another bug #311 but reported error is different. In my case expressions do not work at all.

**Comment by aangelisc** [comment] 2022-10-24 12:35
Thanks for the report @kostrse, I can confirm I've reproduced this and I'm investigating the cause 😊

**Comment by aangelisc** [comment] 2022-10-24 16:34
I've identified the issue is because of [this](https://github.com/grafana/grafana/blob/e48fac9d91ba25e4e3b45fda33f3dc40e662a4c6/public/app/features/expressions/ExpressionDatasource.ts#L29) line. As ADX has the `expression` property defined (but as an object), the `replace` property does not exist which causes this error.  I'll have a look at a fix for this 😊

**Comment by aangelisc** [comment] 2022-10-26 11:38
On further investigation this seems to be a bug in Grafana backend where the incorrect datasource reference is used. Issue [here](https://github.com/grafana/grafana/issues/57663).

**Closed** 2022-11-21 12:09 UTC
Labels: type/bug, datasource/ADX
