### ISSUE TITLE
tsdb.HandleRequest() failed to convert dataframe "" to tsdb.TimeSeriesSlice: input frame is not recognized as a time series

### ISSUE THREAD

**Issue by StupidScience** [grafana/azure-data-explorer-datasource#207] opened 2021-02-08 17:29 UTC
Hello.

Got an error on alerts:
```
tsdb.HandleRequest() failed to convert dataframe "" to tsdb.TimeSeriesSlice: input frame is not recognized as a time series
```

Issue looks similar to https://github.com/grafana/grafana/issues/26897, however it's not fixed on latest grafana version - 7.4.0.
Azure Data Explorer Datasource version is 3.3.2

Our query looks like
```
let Step = iff(timespan($__timeInterval) < timespan(60000ms), timespan(60000ms), timespan($__timeInterval));
TableName
| where $__timeFilter(Timestamp)
| where Level == 'Error'
| make-series Value=count() default=0 on Timestamp from $__timeFrom to $__timeTo step Step by Level
```

Also changing `default` to `=1` in `make-series` statement make no sense.

Any suggestions or workaround?
Thanks in advance?

**Comment by joshhunt** [comment] 2021-02-17 12:08
@kylebrandt this sounds the issue that was fixed in https://github.com/grafana/grafana/pull/26903. Thoughts?

**Comment by joshhunt** [comment] 2021-03-29 11:08
@StupidScience I know it's been a while, but is this still happening with the latest version of this ADX plugin?

Does it only happen for alerts, or also in the query editor when editing a panel?

Are you able to supply a copy-pasteable reproduction query that shows the error using the [datatable](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatableoperator?pivots=azuredataexplorer) operator (that way it doesnt rely on the tables you have in your ADX instance)?

**Comment by nanirover** [comment] 2021-04-01 15:49
I'm experiencing the above error after upgrading the grafana to 7.1.1 using helm, Any thoughts on how we can fix that?
Data source we are using Azure Monitor and App-insights. 

Thanks

**Comment by joshhunt** [comment] 2021-04-06 10:02
Hi @nanirover - For Azure Monitor please file a bug to [grafana/grafana](https://github.com/grafana/grafana/issues/new/choose) with as much detail as possible (screenshots, sample queries, etc)

If the problem is with a KQL query (such as Logs or Insights Analytics), a sample query using the [datatable operator](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatableoperator?pivots=azuredataexplorer) would be greatly appreciated.

**Closed by joshhunt** 2021-04-06 10:02 UTC
Labels: bug, needs investigation

**Comment by spacentropy** [comment] 2021-07-08 06:43
This happens because the input of `make-series` operator is empty. The fix is to use `MakeSeriesParameters` `kind=nonempty`. This way `make-series` will always produce default result.
e.g.

```kql
T | make-series kind=nonempty PriceAvg=avg(Price) default=0
on Purchase from datetime(2016-09-10) to datetime(2016-09-13) step 1d by Supplier, Fruit
```
will always produce time-series with zeros even if T is empty.
