### ISSUE TITLE
Edit KQL button does not display a panel letting me edit KQL

### ISSUE THREAD

**Issue by robeving** [grafana/azure-data-explorer-datasource#325] opened 2022-02-24 15:04 UTC
**What happened**:
I have successfully install the plugin and querying my data with the builder interface. I now want to use much more complex KQL queries which require me to use a custom query. I am expecting to click the Edit KQL button and be presented with a box to enter whatever text I like. I press the button and the UI creates a large area under the button but this area does not contain a text box.

**What you expected to happen**:
Text box appears to enter KQL.

**How to reproduce it (as minimally and precisely as possible)**:
Click Edit KQL button

**Screenshots**
![image](https://user-images.githubusercontent.com/38658282/155549927-a5b846d3-15e1-4bb6-a3ff-86b310015935.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: 8.33
- Plugin version: 3.6.1
- OS Grafana is installed on: Linux
- User OS & Browser: Edge/Chrome
- Others:

**Comment by sunker** [comment] 2022-02-25 08:44
Thanks for creating this issue @robeving. 

I'm afraid I'm not able to reproduce the problem. Would you be able to check for errors in the javascript console and report back here if any?

**Comment by andresmgot** [comment] 2022-02-25 08:54
I cannot find a reference but this is a known issue. If the Monaco editor bundled with Grafana is loaded and then you try to use the one bundled by ADX you get the error: `Uncaught TypeError: Cannot read properties of undefined (reading 'kustoDefaults')` and the code editor doesn't load. As a workaround, you can set up ADX as the default data source so no other code editor is loaded before ADX.

This will be fixed once we work on  #288

**Comment by taleena** [comment] 2022-05-03 17:47
@andresmgot is this now resolved given the linked issues are now closed, and which release is this in?

**Comment by vickyyyyyyy** [comment] 2022-05-03 18:05
I'm guessing we need a new release to go out with the new editor changes? The last release was in March: https://github.com/grafana/azure-data-explorer-datasource/releases/tag/v3.7.1 and it looks like the new editor (which should resolve this) has been worked on since?

**Comment by andresmgot** [comment] 2022-05-05 07:33
yes, we need to release a new major version (4.0) so we need to think the best timing for it

**Comment by taleena** [comment] 2022-05-17 15:49
This is released as of today.

**Closed by taleena** 2022-05-17 15:49 UTC
Labels: type/bug, datasource/ADX

**Comment by hfleitas** [comment] 2022-05-23 21:02
Happening in Azure Managed Grafana 8.4.5, targets 3.7.1
