### ISSUE TITLE
Datasource not found error for some users on loading dashboards

### ISSUE THREAD

**Issue by shahdevangp** [grafana/azure-data-explorer-datasource#371] opened 2022-04-28 12:38 UTC
Hello,

Some users are facing the error "Templating: Failed to upgrade legacy queries Datasource i690Gzynk was not found". See the screenshots. I have built these dashboards and I am able to see the dashboards correctly. I don't get any error. Other users are getting this error. I have double-checked the data source settings, and everything looks ok. 

![MicrosoftTeams-image (29)](https://user-images.githubusercontent.com/46785787/165753484-192795c1-e653-4d82-9343-66c55143468c.png)
![MicrosoftTeams-image (28)](https://user-images.githubusercontent.com/46785787/165753491-e96094ab-c4e3-4751-bb98-cc3edcf6d958.png)

**Comment by andresmgot** [comment] 2022-04-28 14:51
Hi @shahdevangp,

The problem is that the UID of the data source in your Grafana instance is not the same than the one in which the dashboard is imported. To share a dashboard, you need to create a dashboard variable for the data source. Go to settings > variables and add a new variable for the data source:

![Screenshot from 2022-04-28 16-47-35](https://user-images.githubusercontent.com/4025665/165780277-816e2297-0390-4518-a79c-e87af25b59a7.png)

Then you can reference that variable in your panels:

![Screenshot from 2022-04-28 16-50-43](https://user-images.githubusercontent.com/4025665/165780616-96fff7ce-1f5f-437b-ab89-c2d2416d23b6.png)

**Comment by shahdevangp** [comment] 2022-04-28 15:02
We have not imported any dashboards. We have been working in the same instance. Also, if there is a mismatch in the UID, then it should be for everyone and not just for a few users. When I load the dashboard, I don't get any errors. Other users are getting this error.

**Comment by andresmgot** [comment] 2022-04-28 15:22
Got it, if it's the same instance then it could be that those users don't have [permissions to access the data source](https://grafana.com/docs/grafana/latest/enterprise/datasource_permissions/)?

If that is not the case, to try to reproduce the issue, how have you defined the variables?

**Comment by shahdevangp** [comment] 2022-04-28 15:32
Check the screenshots below on how the variables have been defined.

![image](https://user-images.githubusercontent.com/46785787/165789128-2cb73f0f-ffa9-4355-aae1-dbb0bdedf7c2.png)
![image](https://user-images.githubusercontent.com/46785787/165789240-48d74497-49ec-4302-9339-7fa966a04b73.png)

**Comment by shahdevangp** [comment] 2022-04-28 15:33
They were able to see the dashboard yesterday. They cant see it today. I can put my finger on what changed between yday and today.

**Comment by andresmgot** [comment] 2022-04-29 08:50
The variable definition seems fine.

> then it could be that those users don't have [permissions to access the data source](https://grafana.com/docs/grafana/latest/enterprise/datasource_permissions/)?

Can you check if this can be the case? Something should have changed in the administration side that caused this, does not seem a plugin issue.

**Comment by shahdevangp** [comment] 2022-05-10 10:00
It was a permission issue. Users were granted the right permissions and this error went away. I think the error message could be more helpful as it did not point to a permission issue.

**Comment by yaelleC** [comment] 2022-05-10 13:25
Thanks for letting us know @shahdevangp 
I have raised an issue to improve our error messaging

Closing this as resolved

**Closed by yaelleC** 2022-05-10 13:25 UTC
Labels: question, datasource/ADX
