### ISSUE TITLE
Authentication issue with Azure US Government cloud

### ISSUE THREAD

**Issue by floushee** [grafana/azure-data-explorer-datasource#235] opened 2021-06-01 07:44 UTC
I just tested the 3.5.0 release against an Azure US Government ADX. The credentials are ok as I use the same to query the US Government ADX with a custom fork of the azure-data-explorer-datasource plugin (hardcoded token URL).

With the new 3.5.0 release I suddenly get the following error message:
`t=2021-06-01T07:34:36+0000 lvl=eror msg="failed to retrieve azure access token" logger=plugins.backend pluginId=grafana-azure-data-explorer-datasource error="invalid_request AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: c4aed9b8-f409-4986-8293-f7c2ed184303\r\nCorrelation ID: 2f1e53c6-b034-4f46-baa9-64f5a6524cf7\r\nTimestamp: 2021-06-01 07:34:36Z"`

**Comment by floushee** [comment] 2021-06-01 07:58
I think it is related to the scope (pkg/azuredx/datasource.go ). I created a custom version of this plugin once and I had to use _https://epmgcc.usgovarizona.kusto.usgovcloudapi.net/.default_ instead of _https://kusto.kusto.windows.net/.default"_ to make it work.

**Comment by sunker** [comment] 2021-06-01 13:41
Thanks for reporting this @floushee. I'll take a look asap.

**Comment by sunker** [comment] 2021-06-01 15:01
@floushee it looks like the scope that you used is the same as the cluster url, no? I've been looking in the azure docs for information about what scope to use for the different clouds, but haven't found anything.

**Comment by floushee** [comment] 2021-06-01 16:26
@sunker that is correct. I can give you some more information of my customization:
`
conf := clientcredentials.Config{
		ClientID:     c.ClientID,
		ClientSecret: c.Secret,
		TokenURL:     "https://login.microsoftonline.us/" + c.TenantID + "/oauth2/v2.0/token",
		Scopes:       []string{"https://CLUSTER.usgovarizona.kusto.usgovcloudapi.net/.default"},
	}
`
Not sure if the problem is related to the scope but at least there are differences as ADX clusters in public Azure clouds have an URI containing usto.windows.net instead of the US Government ADX deployments which use kusto.usgovcloudapi.net.

**Comment by sunker** [comment] 2021-06-03 11:49
Thanks for details! I think it's very likely this problem is related to the scope. 
I don't have access to any nation clouds to test this, so before we make any new releases I'd like to get it confirmed from Microsoft that we're on the right track. I'll try to get in contact with someone from the adx team.

**Comment by vladikbr** [comment] 2021-06-16 07:33
The scope is correct.
The problem is that you are using AAD endpoint of the public cloud to authenticate to a USGov resource, and that's not possible. In order to work in USGov, you need to 1) provision your SP in the USGov cloud and 2) use the appropriate AAD endpoint for authentication - https://login.microsoftonline.us.

**Comment by sunker** [comment] 2021-06-16 14:22
Thanks for your reply @vladikbr. I think we're already using that endpoint. See code for handling that [here](https://github.com/grafana/azure-data-explorer-datasource/blob/263fa68bb97aa042b35856da6a56bb09e21c686c/pkg/azuredx/tokenprovider/token_provider.go#L56-L68).

**Comment by vladikbr** [comment] 2021-06-22 18:29
@sunker, have you provisioned a service principal in the USGov cloud? Because you need both (1) and (2) from my reply above.
Working with USGov AAD endpoint with public cloud identities cannot work.

**Comment by sunker** [comment] 2021-06-23 05:12
@vladikbr I don't have access to national clouds myself, so not able to test this. 

But if I understand this correctly, for US Gov cloud
* scope ` https://kusto.kusto.windows.net/.default` is correct 
* AAD endpoint `https://login.microsoftonline.us` is correct 

Then it's only a matter of configuring the service principal correctly for the cloud? 

@floushee are you sure your SP is provisioned for US gov cloud?

**Comment by floushee** [comment] 2021-06-23 06:30
My service principal is correct. We use the same principal with a custom grafana setup -> grafana 7.5.6, adx explorer plugin 3.4.0, and we only replaced the hardcoded login.microsoftonline.com in the pgk/azureadx/azureadx.go:

conf := clientcredentials.Config{
  ClientID:     c.ClientID,
  ClientSecret: c.Secret,
  TokenURL:     "https://login.microsoftonline.us/" + c.TenantID + "/oauth2/v2.0/token",
  Scopes:       []string{"https://ouradxcluster.usgovarizona.kusto.usgovcloudapi.net/.default"},
}

and it is working. But if we use the same service principal credentials in with the new adx, we get errors.

**Comment by floushee** [comment] 2021-07-16 09:46
I managed to patch the 3.5.0 version for us by fixing this file:
https://github.com/grafana/azure-data-explorer-datasource/blob/master/pkg/azuredx/datasource.go

First you define a constant and don't use it:
`const AdxScope = "https://kusto.kusto.windows.net/.default"`
because you define it again here:
`tokenProvider := tokenprovider.NewAccessTokenProvider(tokenCache, datasourceSettings.ClientID, datasourceSettings.TenantID, datasourceSettings.AzureCloud, datasourceSettings.Secret, []string{"https://kusto.kusto.windows.net/.default"})`

Next, the scope you have hardcoded does not work in azure government. I had to replace it with:
https://OURCLUSTER.usgovarizona.kusto.usgovcloudapi.net/.default
and it did work. 

We can set something up to fix this together when you reach out to me: dominik.deutsch@gmail.com

**Comment by floushee** [comment] 2021-07-16 11:12
I have added a pull request based on our version (tested with the public and the government cloud): https://github.com/grafana/azure-data-explorer-datasource/pull/250

**Comment by joshhunt** [comment] 2021-07-21 13:13
This issue also exists for Azure China cloud, so we should fix this for all national clouds https://github.com/grafana/azure-data-explorer-datasource/issues/244

**Comment by floushee** [comment] 2021-07-21 14:00
Based on the information of #244 I tried to use https://kusto.kusto.usgovcloudapi.net/.default and also https://kusto.kusto.usgovcloudapi.us/.default. Both are not working. The only working solution in US Government is still to use the cluster url and append the /.default as a scope.

**Comment by andresmgot** [comment] 2022-03-14 16:03
Fixed in https://github.com/grafana/azure-data-explorer-datasource/pull/258 (and released in 3.7.1)

**Closed by andresmgot** 2022-03-14 16:03 UTC
Labels: type/bug, datasource/ADX
