### ISSUE TITLE
metric request error

### ISSUE THREAD

**Issue by ManojRaheja** [grafana/azure-data-explorer-datasource#55] opened 2020-01-08 19:16 UTC
I am getting metric request error while connecting to Azure Data Explorer cluster. The App ID and Key is correct and I suspect the length of the cluster URL may be an issue. The URL I am using is 52 characters long.

**Comment by aykutoezdogan** [comment] 2020-01-14 06:59
@ManojRaheja 
could you please check if grafana-server is already running? I had the same issue and the solution was that grafana was already running.
Our URL also over 52, so I think you should give it a try.

**Comment by srclosson** [comment] 2020-01-14 21:12
@ManojRaheja : A screenshot showing the error would also be helpful as well

**Comment by srclosson** [comment] 2020-02-10 18:16
Impacting a paying customer. Looking to get this into the next sprint.

**Comment by srclosson** [comment] 2020-03-04 22:51
Duplicate of #63

**Closed by srclosson** 2020-03-04 22:51 UTC
Labels: bug, effort/small, priority/high
