### ISSUE TITLE
Access token scope should not be hard coded as https://kusto.kusto.windows.net/.default for Azure China

### ISSUE THREAD

**Issue by casperlw** [grafana/azure-data-explorer-datasource#244] opened 2021-07-06 01:03 UTC
Failed to config the data source for Grafana on Azure China as the access token scope is hard coded as https://kusto.kusto.windows.net/.default

For Azure China the scope should be https://kusto.kusto.chinacloudapi.cn/.default

**Comment by sarahzinger** [comment] 2021-07-20 21:09
somewhat relates to https://github.com/grafana/azure-data-explorer-datasource/pull/250

**Comment by joshhunt** [comment] 2021-07-21 13:13
This issue is _somewhat_ of a dupe of #235, so we'll close this one in favor of that, and make sure we fix this for all national clouds

**Closed by joshhunt** 2021-07-21 13:13 UTC
Labels: type/bug
