### ISSUE TITLE
Feature Request: Pass Grafana userid to ADX as a client request property

### ISSUE THREAD

**Issue by brycefisher** [grafana/azure-data-explorer-datasource#166] opened 2020-10-02 18:04 UTC
**Use Case**
 - I want to audit which user is sending queries (say from the "Explore" page in Grafana) to notify users about inefficent/dangerous queries
 - Grafana sends some representation of the user executing the query with the request as a client request property
 - Monitoring downstream can identify the user and trigger a slack message or other notification to that user if high impact queries are detected

**Notes**
 - Key spot in Adx package: https://github.com/grafana/azure-data-explorer-datasource/blob/f26d6f3d4fdc4a1b9c09c1305a2ccb5b3a0d8f92/pkg/azuredx/azuredx.go#L148
 - Documentation on [`User` named property](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/request-properties#the-user-x-ms-user-named-property)

**Challenges**
 - I'm uncertain if Grafana provides this information to all plugins by default, or if this would require changes to the main server application
 - Can Grafana easily represent alert queries' user somehow already?

**Comment by gilkgit** [comment] 2020-10-04 08:28
In addition to this ticket (Which I think is a duplicate of an older open ticket) - 
It will also be useful to add the the dashboard name to the Kusto request, so we'll be able to easily find the offending dashboard from Kusto

**Comment by brycefisher** [comment] 2020-10-04 15:16
Overall, I think that makes sense. I would favor dashboard ID or url, since users can rename the panel and I don't believe there are uniqueness guarrantees on dashboard names.

Also, we could pass through the panel ID with the dashboard ID.

For all the functionality above, I would look at altering how request ID's activity name is generated in above linked method.

**Comment by mckn** [comment] 2020-10-07 15:18
Great idea and something we easily could add!

**Comment by brycefisher** [comment] 2020-10-08 21:57
@mckn if I wanted to contribute a PR for this, are there any pointers you could provide me?

**Comment by brycefisher** [comment] 2021-01-05 23:29
@mckn would you accept a well written PR for this feature? It seems like something I could possibly figure out and would be extremely valuable to me personally :-)

**Comment by joshhunt** [comment] 2021-01-08 13:25
@brycefisher Sure, go ahead! Let us know if you have any questions.

**Comment by brycefisher** [comment] 2021-01-09 15:47
So, I starting playing with this and ran into a couple issues:

- Currently, ADX won't display the client provided `x-ms-user` value in `.show queries` and friends. I've started a thread with engineers at Microsoft, but currently there's no way to find the provided value :-/ My thought here is to abuse the `x-ms-app` and/or `x-ms-client-id` headers to pass User.Email value somewhere it could be useful, and also pass it in the `x-ms-user-id` header
- I'm pretty sure that backend plugins in go don't currently get the name of the panel or dashboard at all (not a specific ADX plugin issue -- more of an overall Grafana API design thing). We could try to work on changing API between Grafana and plugins, but it doesn't look like we can do this purely from the plugin's codebase.

**Comment by brycefisher** [comment] 2021-01-15 19:47
So, the username in Grafana is now passed to Grafana in a couple of headers in v3.3.0 🎊 !!

**Closed** 2021-02-02 09:58 UTC
Labels: enhancement
