### ISSUE TITLE
Bug: Templating Template variables could not be initialized: undefined

### ISSUE THREAD

**Issue by dasakhar** [grafana/azure-data-explorer-datasource#77] opened 2020-02-25 12:30 UTC
Hey,

After updating to the latest datasource plugin version 2.04 I'm unable to define variables in my dashboards using the Azure data explorer query.

I'm receiving the following error: Templating
Template variables could not be initialized: undefined

![Error](https://user-images.githubusercontent.com/61460930/75247799-6c9e7600-57db-11ea-9a8d-098b034df4d2.PNG)

**Comment by gilkgit** [comment] 2020-02-25 18:25
Duplicate of #61

**Comment by mdfareed2001** [comment] 2020-09-27 10:21
I am also facing the same issue.

**Comment by mano1080881** [comment] 2020-10-20 05:31
HI Any temprory workarround for this Issue

**Comment by sunker** [comment] 2021-02-02 10:42
Closing this since it's a dupe of #61

**Closed by sunker** 2021-02-02 10:42 UTC
