### ISSUE TITLE
It would be nice if you could make sure that when adding a new query the default query will not fail

### ISSUE THREAD

**Issue by gilkgit** [grafana/azure-data-explorer-datasource#100] opened 2020-07-26 07:48 UTC
It would be nice if the default query that one gets when adding a new ADX query would not fail out of the box.
This could be achieved by using datatable[] or print.

One example for the pain caused from the default failing query is that the Text plugin doesn't show the queries pane but it does have the queries behind it, so every time someone creates a text visualization the Text visualization shows a constant obscure error because of the default failing ADX query.
The way to fix is to change to a visualization that doesn't hide the failing ADX query, delete the query and then switch back to the Text vis (but people don't know why they get the failure and how to fix).
I'm not saying that the best way to deal with that Text issue is to create a working query (a better way would be if the text plugin would know not to run queries), but this goes to show that when you leave broken parts around people will eventually step on them.

Also, when you create a visualization, you have to break the flow of thought to handle that pesky default query that otherwise would keep failing until you fix it, and if you'd rather first handle the visualization adjustments and only then attend to the query, then you're out of luck.

if you use a datatable[] you can set a default timeseries with a few rows so that people will be able to just start working after adding the visualization.

**Comment by sunker** [comment] 2021-02-02 10:24
Thanks for reporting this @gilkgit. Can't reproduce this - think it was fixed in one of our latest releases.

**Closed by sunker** 2021-02-02 10:24 UTC
