### ISSUE TITLE
ADX data source plugin consuming a large amount of memory

### ISSUE THREAD

**Issue by yaelleC** [grafana/azure-data-explorer-datasource#436] opened 2022-07-22 10:26 UTC
**What happened**:

Related to [escalation#3328](https://github.com/grafana/support-escalations/issues/3328) 
ADX is consuming too much memory. In case of the escalation, the plugin got OOM killed

**What you expected to happen**:

> ADX plugin should not consistently occupy more than about 500MB memory after serving 2 to 3 ds queries which response size is less than 50MB.

**How to reproduce it (as minimally and precisely as possible)**:

Create an ADX query and try running it for 2-7 days
The `Time Series` format seems to fail more often than the `Table` one 🤷‍♀️ 

**Screenshots**
![Screenshot 2022-07-22 at 12 20 20](https://user-images.githubusercontent.com/42030685/180419256-86cfa526-0bd6-4939-a313-a1df1ef19182.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.0.5-pre
- Plugin version: 4.0.0 - also tried upgrading 4.1.3 (same issue)
- OS Grafana is installed on: HG
- User OS & Browser: Chrome

**Comment by andresmgot** [comment] 2022-08-03 15:52
So, a little bit of analysis of what's happening here. The issue is due to the fact that by default, selecting "Format as: Time series" will convert the Frames (we can refer them as rows of a table) from "Long" to "Wide":

https://github.com/grafana/azure-data-explorer-datasource/blob/e25f75a831651e5825bef183496d778c87624f50/pkg/azuredx/datasource.go#L185-L186

This cause that any field of the table that is either a string or a boolean will be treated as a "label", this is a new dimension for the frame. For example, the following rows:

| time | value | field1 | field2 |
| --- | --- | --- | --- |
| 1:00 | 1 | foo | bar |
| 2:00 | 2 | other | value |

`field1` and `field2` will be new dimensions for the time series, which would generate the following response:

| time | value{field1: foo, field2:bar} | value{field1: foo, field2:value} | value{field1: other, field2:bar} | value{field1: other, field2:value} 
| --- | --- | --- | --- | --- |
| 1:00 | 1 | | | |
| 2:00 |  | | | 2 |

Each one of those cells is a point to draw in the graph. As the number of fields and values grow, the number of points to draw grows exponentially.

The current way of avoiding this issue is simply defining a more complete query. If we add a filter `| where field1 == 'foo'` then we limit that growth. The problem is that queries by default will still hit this issue.

Given that we have two options:

- Change the default format to be "table", this formatting do not include the additional handling so data will be returned as is. The problem with this is that people may find it more difficult to return time series from their data.
- Add a column selection by default. In other data sources (e.g. PostgreSQL), data is filtered by default to use just one numeric value. In the example above, it would mean that by default, the query will be built to return only the fields `time` and `value` which are the minimal necessary to generate a time series. The user can later decide if they want to add more columnns to that (aka labels).

I think that the second is more user friendly and closer to what other data sources do (even though it requires a bit more of effort to implement). WDYT?

**Comment by yaelleC** [comment] 2022-08-04 08:13
@andresmgot , Nice investigation! 🚀 

I agree with your conclusions, turning string/bool values into labels makes the algo have an exponential complexity, ouch! So whatever we can do to make the number of columns smaller 👍 

Were you thinking adding fields after `from` to select columns (similar to what Postgress is doing)? What about users that edit KQL directly, would the query be populated by default with `| project`  (not sure we actually have a template query that is entered in the Kusto editor?)

**Comment by andresmgot** [comment] 2022-08-04 08:48
> Were you thinking adding fields after `from` to select columns (similar to what Postgress is doing)?

Yes, something like (being the new field a multi-select field):

![Screenshot from 2022-08-04 10-46-21](https://user-images.githubusercontent.com/4025665/182804767-78a49926-6c42-48bd-8b38-9b3f437e3ad4.png)

> What about users that edit KQL directly, would the query be populated by default with `| project` (not sure we actually have a template query that is entered in the Kusto editor?)

Yes, the KQL editor is pre-populated with whatever has been generated in the query builder so it will include that by default.

**Comment by andresmgot** [comment] 2022-08-04 11:38
so after further evaluating this, adding a new field in the current editor involves quite a big investment in the current builder which we want to revamp in #391 so it would go away soon :disappointed: . It's probably better to address this issue once that one is done.

In the meantime, we can go with the first option I suggest in [my first comment](https://github.com/grafana/azure-data-explorer-datasource/issues/436#issuecomment-1204141210), setting "Table" as the default format. This is an easy win, since it basically perform as we want, only drawing one time series per numeric value. For example, in this query, the table `DestinyActivities` has 3 numeric fields so it just draw those with no labels (which should work for most users):

![Screenshot from 2022-08-04 13-33-04](https://user-images.githubusercontent.com/4025665/182837859-99823924-91c8-4af1-a832-6bf3631b720b.png)

**Comment by andresmgot** [comment] 2022-08-08 12:32
Merged the default change, this should prevent most of people from accidentally running into this issue. Moving this back to the backlog until https://github.com/grafana/azure-data-explorer-datasource/issues/391 is done.

**Comment by andresmgot** [comment] 2022-09-27 12:52
Done with https://github.com/grafana/azure-data-explorer-datasource/pull/474 and https://github.com/grafana/azure-data-explorer-datasource/pull/476

**Closed by andresmgot** 2022-09-27 12:52 UTC
Labels: enhancement, datasource/ADX
