### ISSUE TITLE
Graph - Series Mode: Sorting

### ISSUE THREAD

**Issue by t-sean** [grafana/azure-data-explorer-datasource#42] opened 2019-10-28 13:55 UTC
The backend seems to be overriding the sorting applied to the query.
```
let events = datatable(timestamp:datetime, metricname:string, value:long)
[
'2019-09-24T00:00:00Z','metric5',47815,
'2019-09-24T00:00:00Z','metric3',9009,
'2019-09-24T00:00:00Z','metric2',227900,
'2019-09-24T00:00:00Z','metric4',40200,
'2019-09-24T00:00:00Z','metric1',536720,
'2019-09-24T00:10:00Z','metric3',9908,
'2019-09-24T00:10:00Z','metric2',227792,
'2019-09-24T00:10:00Z','metric5',56150,
'2019-09-24T00:10:00Z','metric4',42821,
'2019-09-24T00:10:00Z','metric1',539793,
'2019-09-24T00:20:00Z','metric4',51409,
'2019-09-24T00:20:00Z','metric1',520867,
'2019-09-24T00:20:00Z','metric2',243148,
'2019-09-24T00:20:00Z','metric5',48020,
'2019-09-24T00:20:00Z','metric3',10664,
'2019-09-24T00:30:00Z','metric1',530727,
'2019-09-24T00:30:00Z','metric2',238394,
'2019-09-24T00:30:00Z','metric5',35661,
'2019-09-24T00:30:00Z','metric3',10000,
'2019-09-24T00:30:00Z','metric4',44866,
];
events
| summarize sum(value) by metricname, bin(timestamp, 10m)
| top 10 by sum_value desc
```

Shows sorted data in adx
```
metricname	timestamp	sum_value
metric1	2019-09-24T00:10:00Z	539793
metric1	2019-09-24T00:00:00Z	536720
metric1	2019-09-24T00:30:00Z	530727
metric1	2019-09-24T00:20:00Z	520867
metric2	2019-09-24T00:20:00Z	243148
metric2	2019-09-24T00:30:00Z	238394
metric2	2019-09-24T00:00:00Z	227900
metric2	2019-09-24T00:10:00Z	227792
metric5	2019-09-24T00:10:00Z	56150
metric4	2019-09-24T00:20:00Z	51409
```

But series data order changes with refresh of query

![Capture](https://user-images.githubusercontent.com/17075206/67683440-cd21c180-f967-11e9-83b5-dbcb7ceb857a.PNG)

Am I missing something? Thanks.

**Comment by t-sean** [comment] 2019-11-06 14:55
Maybe the issue for me is coming from this?

https://blog.golang.org/go-maps-in-action

"When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. If you require a stable iteration order you must maintain a separate data structure that specifies that order."

I was able to get something working locally, but I really don't know know all the different use cases for time series data.

```golang
func (tr *TableResponse) ToTimeSeries() ([]*datasource.TimeSeries, bool, error) {
...
var keys []string
for rowIdx, row := range resTable.Rows {
...
for _, valueIdx := range valueColumnIdxs {
  colName := resTable.Columns[valueIdx].ColumnName
  series, ok := seriesMap[colName][labels.str]
  if !ok {
    series = &datasource.TimeSeries{}
    series.Name = labels.GetName(colName)
    series.Tags = labels.keyVals
    seriesMap[colName][labels.str] = series
    keys = append(keys, labels.str)
  }
...
}
for _, sm := range seriesMap {
  for _, k := range keys {
  s, ok := sm[k]
  if ok {
    series = append(series, s)
  }
 }
}
```

Also map check may not be necessary

**Comment by joshhunt** [comment] 2021-02-02 11:49
I'm not able to reproduce this any more - I believe this was fixed in the backend SDK since. Feel free to reopen if it's still happening on the latest version

**Closed by joshhunt** 2021-02-02 11:49 UTC
